"""phase1 baseline

Revision ID: 0001_phase1
Revises:
Create Date: 2026-09-29 22:11:46.210169
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import papermind.db.base

revision: str = "0001_phase1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ts", papermind.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("level", sa.String(length=8), nullable=False),
        sa.Column("book_id", sa.String(length=64), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index("ix_audit_cat_ts", ["category", "ts"], unique=False)

    op.create_table(
        "books",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("market", sa.String(length=16), nullable=False),
        sa.Column("segment", sa.String(length=16), nullable=False),
        sa.Column("style", sa.String(length=16), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("halted", sa.Boolean(), nullable=False),
        sa.Column("halt_reason", sa.Text(), nullable=True),
        sa.Column("halted_until", papermind.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("created_at", papermind.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "candles",
        sa.Column("instrument_id", sa.String(length=128), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("ts_open", papermind.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("open", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("high", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("low", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("close", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("volume", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.PrimaryKeyConstraint("instrument_id", "timeframe", "ts_open"),
    )
    op.create_table(
        "equity_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("book_id", sa.String(length=64), nullable=False),
        sa.Column("account", sa.String(length=32), nullable=False),
        sa.Column("ts", papermind.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("balance", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("unrealized", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("equity", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("equity_snapshots", schema=None) as batch_op:
        batch_op.create_index("ix_equity_book_ts", ["book_id", "account", "ts"], unique=False)

    op.create_table(
        "instruments",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("market", sa.String(length=16), nullable=False),
        sa.Column("segment", sa.String(length=16), nullable=False),
        sa.Column("exchange", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("underlying", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("quote_ccy", sa.String(length=8), nullable=False),
        sa.Column("settle_ccy", sa.String(length=8), nullable=False),
        sa.Column("contract_size", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("lot_size", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("tick_size", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("qty_step", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("min_qty", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("expiry", papermind.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("strike", papermind.db.base.DecimalText(length=64), nullable=True),
        sa.Column("broker_token", sa.String(length=64), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("refreshed_at", papermind.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "risk_decisions",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("ts", papermind.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("book_id", sa.String(length=64), nullable=False),
        sa.Column("account", sa.String(length=32), nullable=False),
        sa.Column("actor", sa.String(length=16), nullable=False),
        sa.Column("instrument_id", sa.String(length=128), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("failed_rule_id", sa.String(length=48), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("results", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("risk_decisions", schema=None) as batch_op:
        batch_op.create_index("ix_risk_book_ts", ["book_id", "ts"], unique=False)

    op.create_table(
        "system_state",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at", papermind.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("book_id", sa.String(length=64), nullable=False),
        sa.Column("account", sa.String(length=32), nullable=False),
        sa.Column("ts", papermind.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("amount", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("trade_id", sa.String(length=40), nullable=True),
        sa.Column("fill_id", sa.String(length=40), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ledger_entries", schema=None) as batch_op:
        batch_op.create_index("ix_ledger_book_account_ts", ["book_id", "account", "ts"], unique=False)

    op.create_table(
        "trades",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("book_id", sa.String(length=64), nullable=False),
        sa.Column("account", sa.String(length=32), nullable=False),
        sa.Column("actor", sa.String(length=16), nullable=False),
        sa.Column("instrument_id", sa.String(length=128), nullable=False),
        sa.Column("direction", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("qty", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("contract_size", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("leverage", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("avg_entry", papermind.db.base.DecimalText(length=64), nullable=True),
        sa.Column("avg_exit", papermind.db.base.DecimalText(length=64), nullable=True),
        sa.Column("initial_sl", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("current_sl", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("target", papermind.db.base.DecimalText(length=64), nullable=True),
        sa.Column("trailing", sa.JSON(), nullable=True),
        sa.Column("initial_risk", papermind.db.base.DecimalText(length=64), nullable=True),
        sa.Column("gross_pnl", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("charges", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("funding", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("net_pnl", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("r_multiple", papermind.db.base.DecimalText(length=64), nullable=True),
        sa.Column("mae", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("mfe", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("exit_reason", sa.String(length=16), nullable=True),
        sa.Column("stale_exit", sa.Boolean(), nullable=False),
        sa.Column("signal_id", sa.String(length=40), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", papermind.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("opened_at", papermind.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("closed_at", papermind.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.create_index("ix_trades_book_status", ["book_id", "account", "status"], unique=False)

    op.create_table(
        "orders",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("trade_id", sa.String(length=40), nullable=False),
        sa.Column("book_id", sa.String(length=64), nullable=False),
        sa.Column("account", sa.String(length=32), nullable=False),
        sa.Column("actor", sa.String(length=16), nullable=False),
        sa.Column("instrument_id", sa.String(length=128), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("purpose", sa.String(length=16), nullable=False),
        sa.Column("qty", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("limit_price", papermind.db.base.DecimalText(length=64), nullable=True),
        sa.Column("trigger_price", papermind.db.base.DecimalText(length=64), nullable=True),
        sa.Column("oco_group", sa.String(length=40), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column("created_at", papermind.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", papermind.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trades.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index("ix_orders_status", ["status"], unique=False)

    op.create_table(
        "fills",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("order_id", sa.String(length=40), nullable=False),
        sa.Column("trade_id", sa.String(length=40), nullable=False),
        sa.Column("ts", papermind.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("price", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("qty", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("reference_price", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("reference_kind", sa.String(length=24), nullable=False),
        sa.Column("slippage", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("liquidity", sa.String(length=8), nullable=False),
        sa.Column("charges", sa.JSON(), nullable=False),
        sa.Column("charges_total", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("stale_price", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fills")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index("ix_orders_status")

    op.drop_table("orders")
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.drop_index("ix_trades_book_status")

    op.drop_table("trades")
    with op.batch_alter_table("ledger_entries", schema=None) as batch_op:
        batch_op.drop_index("ix_ledger_book_account_ts")

    op.drop_table("ledger_entries")
    op.drop_table("system_state")
    with op.batch_alter_table("risk_decisions", schema=None) as batch_op:
        batch_op.drop_index("ix_risk_book_ts")

    op.drop_table("risk_decisions")
    op.drop_table("instruments")
    with op.batch_alter_table("equity_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_equity_book_ts")

    op.drop_table("equity_snapshots")
    op.drop_table("candles")
    op.drop_table("books")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_cat_ts")

    op.drop_table("audit_log")
    # ### end Alembic commands ###
