"""phase2 signals and backtest runs

Revision ID: 0002_phase2
Revises: 0001_phase1
Create Date: 2026-09-29 22:11:46.302042
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import papermind.db.base

revision: str = "0002_phase2"
down_revision: str | None = "0001_phase1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_runs",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", papermind.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("finished_at", papermind.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("backtest_runs", schema=None) as batch_op:
        batch_op.create_index("ix_backtest_created", ["created_at"], unique=False)

    op.create_table(
        "signals",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("ts", papermind.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("book_id", sa.String(length=64), nullable=False),
        sa.Column("instrument_id", sa.String(length=128), nullable=False),
        sa.Column("strategy_id", sa.String(length=48), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("direction", sa.String(length=8), nullable=False),
        sa.Column("entry_ref", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("stop_loss", papermind.db.base.DecimalText(length=64), nullable=False),
        sa.Column("target", papermind.db.base.DecimalText(length=64), nullable=True),
        sa.Column("setup", sa.Text(), nullable=False),
        sa.Column("regime", sa.JSON(), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("decision_by", sa.String(length=16), nullable=False),
        sa.Column("decision_reason", sa.Text(), nullable=False),
        sa.Column("executed", sa.Boolean(), nullable=False),
        sa.Column("trade_id", sa.String(length=40), nullable=True),
        sa.Column("baseline_trade_id", sa.String(length=40), nullable=True),
        sa.Column("risk_rule_blocked", sa.String(length=48), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("signals", schema=None) as batch_op:
        batch_op.create_index("ix_signals_book_ts", ["book_id", "ts"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("signals", schema=None) as batch_op:
        batch_op.drop_index("ix_signals_book_ts")

    op.drop_table("signals")
    with op.batch_alter_table("backtest_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_backtest_created")

    op.drop_table("backtest_runs")
    # ### end Alembic commands ###
